title: Jekyll Website Template
author:
  name: GitHub User
  email: your-email@domain.com

description: >
  Jekyll Website Template.

nav_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content